In [1]:
import pandas as pd

path = '/home/asanchez/code/asanchez/LLMScholar-Personas/data/data/semantic_scholar_data/clean/Researchers_Deduplicated_Genderize_Namsor.parquet'
df = pd.read_parquet(path)

print(f'Shape: {df.shape}')
print(f'Columns: {df.columns.tolist()}')
df.head()

Shape: (6686108, 17)
Columns: ['Researcher_id', 'First_year', 'Last_year', 'Ranking_position_citations', 'Citations', 'Productivity', 'Collaborations', 'Field', 'Gender', 'Name', 'Probability', 'Clean_standarized_name', 'Career_age', 'Number_of_genders', 'Gender_Namsor', 'Gender_probability_Namsor', 'Combined_gender']

,Researcher_id,First_year,Last_year,Ranking_position_citations,Citations,Productivity,Collaborations,Field,Gender,Name,Probability,Clean_standarized_name,Career_age,Number_of_genders,Gender_Namsor,Gender_probability_Namsor,Combined_gender
0,66098311.0,1964.0,2016.0,3,30575,84,33,Sociology,None,A. Giddens,NaN,None,55.0,0,None,0.0,None
1,97923787.0,1966.0,2019.0,17,13742,44,24,Sociology,male,Michel Foucault,0.747290,MICHEL,53.0,1,None,0.0,male
2,2906196.0,1972.0,2010.0,23,11975,40,14,Sociology,male,Michel Callon,0.747290,MICHEL,47.0,1,None,0.0,male
3,9828516.0,1973.0,2018.0,25,10958,67,11,Sociology,male,John Urry,0.995768,JOHN,46.0,1,None,0.0,male
4,40048711.0,1945.0,1955.0,32,9458,3,6,Sociology,male,Philipp Weintraub,1.000000,PHILIPP,74.0,1,None,0.0,male

In [2]:
df.head(25)

,Researcher_id,First_year,Last_year,Ranking_position_citations,Citations,Productivity,Collaborations,Field,Gender,Name,Probability,Clean_standarized_name,Career_age,Number_of_genders,Gender_Namsor,Gender_probability_Namsor,Combined_gender
0,66098311.0,1964.0,2016.0,3,30575,84,33,Sociology,None,A. Giddens,NaN,None,55.0,0,None,0.0,None
1,97923787.0,1966.0,2019.0,17,13742,44,24,Sociology,male,Michel Foucault,0.747290,MICHEL,53.0,1,None,0.0,male
2,2906196.0,1972.0,2010.0,23,11975,40,14,Sociology,male,Michel Callon,0.747290,MICHEL,47.0,1,None,0.0,male
3,9828516.0,1973.0,2018.0,25,10958,67,11,Sociology,male,John Urry,0.995768,JOHN,46.0,1,None,0.0,male
4,40048711.0,1945.0,1955.0,32,9458,3,6,Sociology,male,Philipp Weintraub,1.000000,PHILIPP,74.0,1,None,0.0,male
5,9334255.0,1963.0,2015.0,41,8865,22,16,Sociology,male,Michael T. Hannan,0.995020,MICHAEL,56.0,1,None,0.0,male
6,15017632.0,1960.0,2008.0,43,8555,15,9,Sociology,male,Anthony Giddens,0.995044,ANTHONY,59.0,1,None,0.0,male
7,1958931.0,1970.0,2019.0,57,7295,64,16,Sociology,male,Trevor Pinch,0.996052,TREVOR,49.0,1,None,0.0,male
8,115990619.0,1974.0,1981.0,67,6566,3,4,Sociology,male,Milton Ehre,0.994747,MILTON,45.0,1,None,0.0,male
9,118391685.0,1983.0,2015.0,74,6136,26,13,Sociology,female,Doreen Massey,0.998746,DOREEN,36.0,1,None,0.0,female
10,65867835.0,1992.0,2013.0,78,6053,11,6,Sociology,female,Kathryn Sikkink,0.997573,KATHRYN,27.0,1,None,0.0,female
11,143916791.0,1990.0,2018.0,94,5228,35,6,Sociology,female,Raewyn Connell,1.000000,RAEWYN,29.0,1,None,0.0,female
12,115774243.0,1835.0,1916.0,96,5137,2,4,Sociology,male,Harold J. Laski,0.995200,HAROLD,184.0,1,None,0.0,male
13,108685382.0,1835.0,1938.0,98,5136,2,4,Sociology,male,Phillips Bradley,1.000000,PHILLIPS,184.0,1,None,0.0,male
14,114088571.0,1835.0,1835.0,99,5136,1,4,Sociology,male,Donald J. Pierce,0.996066,DONALD,184.0,1,None,0.0,male
15,153108450.0,1981.0,2019.0,105,4924,23,17,Sociology,male,John Gaventa,0.995768,JOHN,38.0,1,None,0.0,male
16,116375803.0,1964.0,2007.0,116,4609,31,19,Sociology,female,Mary Douglas,0.996333,MARY,55.0,1,None,0.0,female
17,144872409.0,1963.0,2019.0,120,4501,17,6,Sociology,male,Michael Halliday,0.995020,MICHAEL,56.0,1,None,0.0,male
18,97527797.0,1974.0,2003.0,127,4445,10,10,Sociology,male,Dietrich Rueschemeyer,0.919285,DIETRICH,45.0,1,None,0.0,male
19,108148487.0,1958.0,1975.0,128,4444,4,7,Sociology,male,Donald Stokes,0.996066,DONALD,61.0,1,None,0.0,male
20,89210323.0,1955.0,1987.0,135,4333,10,11,Sociology,male,Heinz Eulau,1.000000,HEINZ,64.0,1,None,0.0,male
21,69057836.0,1971.0,2020.0,138,4319,152,18,Sociology,male,Michael W. Apple,0.995020,MICHAEL,48.0,1,None,0.0,male
22,100698892.0,1979.0,2018.0,142,4252,25,12,Sociology,female,Theda Skocpol,1.000000,THEDA,40.0,1,None,0.0,female
23,40363547.0,1980.0,1980.0,150,4064,1,2,Sociology,male,Alvin Toffler,0.993079,ALVIN,39.0,1,None,0.0,male
24,5030784.0,1972.0,2012.0,159,3942,22,3,Sociology,male,Michael Eraut,0.995020,MICHAEL,47.0,1,None,0.0,male