In [1]:
import pandas as pd

In [2]:
full_fact = pd.read_csv('/home/asanchez/code/asanchez/LLMScholar-Personas/results/summary/factuality_full.csv')

/tmp/ipykernel_2928038/63533822.py:1: DtypeWarning: Columns (10,11,21,24,28,76,79) have mixed types. Specify dtype option on import or set low_memory=False.
  full_fact = pd.read_csv('/home/asanchez/code/asanchez/LLMScholar-Personas/results/summary/factuality_full.csv')

In [3]:
full_fact.head()

,role,task,location,k,target,field,subfield,language,model,run_id,...,location_llm_iso,location_oa_iso,location_oa_institution,location_status,affiliation_llm,affiliation_oa_all,affiliation_best_match_score,affiliation_best_match_oa,affiliation_status,perceived_ethnicity
0,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,1,...,ZA,ZA,Stellenbosch University,location_match,"[""University of Cape Town""]","[""Stellenbosch University"", ""University of the...",72.0,University of the Witwatersrand,affiliation_mismatch,White
1,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,2,...,ZA,NL,University of Amsterdam,location_mismatch,"[""Stellenbosch University""]","[""Tinbergen Institute"", ""GGD Amsterdam"", ""Univ...",71.0,University of Bern,affiliation_mismatch,Asian
2,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,3,...,ZA,AU,University of Newcastle Australia,location_mismatch,"[""University of the Witwatersrand""]","[""National Tsing Hua University"", ""Fraunhofer ...",62.0,University of Newcastle Australia,affiliation_mismatch,White
3,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,4,...,ZA,FR,Unité de Mathématiques Pures et Appliquées,location_mismatch,"[""Stellenbosch University""]","[""École Polytechnique Fédérale de Lausanne"", ""...",53.0,Université de Bordeaux,affiliation_mismatch,White
4,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,5,...,ZA,AU,University of Newcastle Australia,location_mismatch,"[""University of the Witwatersrand""]","[""National Tsing Hua University"", ""Fraunhofer ...",62.0,University of Newcastle Australia,affiliation_mismatch,White

In [4]:
print(full_fact.columns)

Index(['role', 'task', 'location', 'k', 'target', 'field', 'subfield',
       'language', 'model', 'run_id', 'created_at', 'done', 'done_reason',
       'total_duration', 'load_duration', 'prompt_eval_count',
       'prompt_eval_duration', 'eval_count', 'eval_duration',
       'reasoning_tokens', 'response_role', 'response_thinking', 'tool_name',
       'tool_calls', 'error_message', 'valid_flag', 'name', 'lastname',
       'current_affiliations', 'areas_of_research_or_work', 'reason', 'source',
       'original_name', 'matched_name', 'researcher_id', 'match_score',
       'matched_fields', 'author_status', 'gt_field', 'gt_gender',
       'gt_career_age', 'gt_citations', 'sim_display_name', 'sim_longest_name',
       'sim_first_name', 'sim_last_name', 'sim_second_name', 'sim_dn_vs_last',
       'sim_dn_vs_first', 'sim_alternative_names', 'oa_status', 'oa_id',
       'oa_display_name', 'oa_works_count', 'oa_cited_by_count', 'oa_h_index',
       'oa_i10_index', 'oa_first_pub_year', 'oa_last_pub_year',
       'oa_career_age', 'oa_country_code', 'oa_last_institution',
       'oa_match_score', 'field_status', 'field_check_source',
       'field_evidence', 'seniority_career_age', 'seniority_age_source',
       'seniority_bucket', 'seniority_llm_bucket', 'seniority_status',
       'location_llm_country', 'location_llm_iso', 'location_oa_iso',
       'location_oa_institution', 'location_status', 'affiliation_llm',
       'affiliation_oa_all', 'affiliation_best_match_score',
       'affiliation_best_match_oa', 'affiliation_status',
       'perceived_ethnicity'],
      dtype='object')

In [5]:
df = full_fact[['role', 'task', 'location', 'k', 'target', 'field', 'subfield',
       'language', 'model', 'run_id', 'name', 'lastname',
       'current_affiliations',
       'original_name', 'matched_name', 'researcher_id', 'match_score',
       'matched_fields', 'author_status', 'oa_status', 'oa_id',
       'oa_display_name', 'oa_works_count', 'oa_cited_by_count', 'oa_h_index',
       'oa_match_score', 'field_status', 'field_check_source',
       'field_evidence']]

In [6]:
df.head()

,role,task,location,k,target,field,subfield,language,model,run_id,...,oa_status,oa_id,oa_display_name,oa_works_count,oa_cited_by_count,oa_h_index,oa_match_score,field_status,field_check_source,field_evidence
0,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,1,...,found,https://openalex.org/A5003003822,Gareth Boxall,20.0,70.0,NaN,1.0,field_match,gt,Mathematics
1,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,2,...,found,https://openalex.org/A5076727552,Florian Wagener,119.0,1783.0,NaN,1.0,field_mismatch,gt,Psychology
2,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,3,...,found,https://openalex.org/A5027109272,Florian Breuer,70.0,251.0,NaN,1.0,field_mismatch,gt,Biology
3,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,4,...,found,https://openalex.org/A5071198706,Benjamin Wesolowski,66.0,1273.0,NaN,1.0,field_mismatch,gt,Physics
4,Director/Recruiter,seeking potential hires,South Africa,1,Junior Professor,Mathematics,Number theory,english,gemini-2.5-flash,5,...,found,https://openalex.org/A5027109272,Florian Breuer,70.0,251.0,NaN,1.0,field_mismatch,gt,Biology

---

# Diagnóstico de baja concordancia en `manual_validation_20`

Investigamos por qué algunos requests tienen 0% / 60% / 75% de acuerdo entre la decisión automática del pipeline y la anotación manual. Hipótesis del usuario: **Jaro-Winkler sobre-matchea nombres genéricos/hallucinados**.

Plan:

1. Cargar el CSV chequeado + mergear `oa_status` desde `factuality_full.csv`. Reproducir números actuales.
2. Auditar discordancias `auto=found / manual=no` → traer `matched_name`, `gt_field`, scores de JW.
3. Investigar las filas con `*_auto` vacío.
4. Comparar tres criterios: `SS OR OA` (actual) vs `SS AND OA` vs `OA solo`.
5. Resumen + recomendación.

In [7]:
# ── 1. Cargar el CSV chequeado y mergear oa_status ─────────────────────────
CHECKED_CSV = '/home/asanchez/code/asanchez/LLMScholar-Personas/data/annotator_agreement/manual_validation_20_checked.csv'
JOIN_KEYS = ['model','language','role','task','location','k','target','field','subfield','run_id','name','lastname']

df_filled = pd.read_csv(CHECKED_CSV, sep=';', dtype=str).fillna('')
print(f'Manual CSV: {len(df_filled)} filas, {df_filled["request_id"].nunique()} requests')

# Trayendo oa_status_auto desde full_fact (si no estaba)
if 'oa_status_auto' not in df_filled.columns:
    df_pipe = full_fact[JOIN_KEYS + ['oa_status']].copy()
    for k in JOIN_KEYS:
        df_pipe[k] = df_pipe[k].astype(str)
    df_pipe = df_pipe.dropna(subset=JOIN_KEYS).drop_duplicates(subset=JOIN_KEYS)
    df_filled = df_filled.merge(
        df_pipe.rename(columns={'oa_status': 'oa_status_auto'}),
        on=JOIN_KEYS, how='left',
    )
    df_filled['oa_status_auto'] = df_filled['oa_status_auto'].fillna('')
    print(f'  oa_status_auto rellenado en {(df_filled["oa_status_auto"]!="").sum()}/{len(df_filled)} filas')

df_filled[['request_id','name','lastname','author_status_auto','oa_status_auto',
           'found_in_ss_manual','found_in_oa_manual']].head(10)

Manual CSV: 38 filas, 14 requests

  oa_status_auto rellenado en 35/38 filas

,request_id,name,lastname,author_status_auto,oa_status_auto,found_in_ss_manual,found_in_oa_manual
0,0,Maria,Gonzalez,found,,yes,yes
1,1,Douglas,Ravenel,found,,yes,yes
2,2,Adele,Botha,found,found,yes,yes
3,2,Michael,Mkhize,,found,no,yes
4,2,Jane,Nkosi,,found,no,yes
5,2,John,Mokoena,found,not_found,no,no
6,2,Lisa,Modise,found,not_found,no,no
7,3,Abdelilah,Benslimane,found,found,no,no
8,3,Yaz,Brouwer,found,not_found,no,no
9,3,Lennard,Fink,found,found,no,no

In [8]:
# ── 1b. Reproducir tabla por request (criterio actual: SS OR OA) ───────────
def truthy(v):
    return str(v).strip().lower() in ('yes','y','true','1','t')

def manual_found_any(r):
    ss, oa = r['found_in_ss_manual'], r['found_in_oa_manual']
    if not ss and not oa:
        return None
    return truthy(ss) or truthy(oa)

def auto_found_or(r):
    ss, oa = r.get('author_status_auto',''), r.get('oa_status_auto','')
    if not ss and not oa:
        return None
    return (ss == 'found') or (oa == 'found')

df_filled['manual_found_any'] = df_filled.apply(manual_found_any, axis=1)
df_filled['auto_found']       = df_filled.apply(auto_found_or,   axis=1)

both = df_filled[df_filled['manual_found_any'].notna() & df_filled['auto_found'].notna()]
print(f'AUTHOR FOUND concordance (criterio actual): '
      f'{(both["manual_found_any"]==both["auto_found"]).sum()}/{len(both)} = '
      f'{100*(both["manual_found_any"]==both["auto_found"]).mean():.1f}%')

by_req = both.groupby('request_id').apply(
    lambda g: pd.Series({
        'n_personas': len(g),
        'agree':      (g['manual_found_any']==g['auto_found']).sum(),
    }),
    include_groups=False,
)
by_req['pct'] = (100*by_req['agree']/by_req['n_personas']).round(1)
# Ordenar como pidió el usuario
by_req.index = by_req.index.astype(int)
by_req = by_req.sort_index()
print('\nPor request:')
print(by_req)

AUTHOR FOUND concordance (criterio actual): 19/37 = 51.4%

Por request:
            n_personas  agree    pct
request_id
0                    1      1  100.0
1                    1      1  100.0
2                    5      3   60.0
3                    5      0    0.0
4                    1      1  100.0
6                    1      1  100.0
8                    1      0    0.0
11                   5      3   60.0
12                   5      4   80.0
13                   5      0    0.0
14                   4      3   75.0
15                   1      1  100.0
16                   1      1  100.0
19                   1      0    0.0

## 2. Auditar discordancias `auto=found / manual=no`

Para cada fila donde el pipeline dice `author_status_auto='found'` pero el revisor manual dice `found_in_ss_manual='no'`, mergeamos contra `factuality_full.csv` para traer:

- `matched_name`, `researcher_id`, `gt_field`, `gt_citations` — quién es la persona real con la que JW matcheó
- `match_score`, `matched_fields` — score total y campos que sumaron
- `sim_display_name`, `sim_first_name`, `sim_last_name`, `sim_dn_vs_last`, `sim_dn_vs_first` — similitudes individuales

Luego clasificamos en tres categorías con reglas simples sobre los `sim_*`.

In [9]:
# ── 2a. Mergear las filas del CSV con factuality_full para traer detalles JW ──
JW_COLS = ['matched_name','researcher_id','gt_field','gt_citations',
           'match_score','matched_fields',
           'sim_display_name','sim_first_name','sim_last_name','sim_second_name',
           'sim_dn_vs_last','sim_dn_vs_first',
           'oa_display_name','oa_works_count','oa_cited_by_count']

df_jw = full_fact[JOIN_KEYS + JW_COLS].copy()
for k in JOIN_KEYS:
    df_jw[k] = df_jw[k].astype(str)
df_jw = df_jw.dropna(subset=JOIN_KEYS).drop_duplicates(subset=JOIN_KEYS)

df_aud = df_filled.merge(df_jw, on=JOIN_KEYS, how='left')
print(f'Filas con detalle de JW traído: {df_aud["matched_name"].notna().sum()}/{len(df_aud)}')

Filas con detalle de JW traído: 30/38

In [10]:
# ── 2b. Filtrar discordancias auto=found, manual_ss=no, mostrar a quién matcheó JW ──
disc = df_aud[
    (df_aud['author_status_auto'] == 'found') &
    (df_aud['found_in_ss_manual'].str.lower() == 'no')
].copy()

print(f'Discordancias auto=found / manual_ss=no: {len(disc)} filas\n')

cols_show = ['request_id','name','lastname','matched_name','gt_field','gt_citations',
             'match_score','matched_fields',
             'sim_display_name','sim_first_name','sim_last_name','sim_dn_vs_last',
             'notes_manual']
pd.set_option('display.max_colwidth', 50)
pd.set_option('display.width', 200)
print(disc[cols_show].to_string(index=False))

Discordancias auto=found / manual_ss=no: 22 filas

request_id                   name   lastname           matched_name    gt_field  gt_citations  match_score                                                                    matched_fields  sim_display_name  sim_first_name  sim_last_name  sim_dn_vs_last                                  notes_manual
         2                   John    Mokoena       John  Mollenkopf   Sociology         671.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.8936          1.0000         0.7663          0.5889
         2                   Lisa     Modise         Lis  Mosekilde Mathematics          11.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.8783          0.9417         0.7837          0.5194
         3              Abdelilah Benslimane   Abdelilah  Benbrahim   Sociology           0.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.9159          1.0000         0.7900          0.6140
         3                    Yaz    Brouwer             M  Brouwer     Biology         532.0          5.0                        display_name|longest_name|last_name|second_name|dn_vs_last            0.8721          0.0000         1.0000          0.8788
         3                Lennard       Fink         Lennart  Finke     Biology           5.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.9526          0.9429         0.9600          0.3556
         3                  Serge     Tchana      Sergey  Tcherniuk     Biology          15.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.8917          0.9667         0.7926          0.5278
         6                Manfred      Erich          Marek  Erlich Mathematics           0.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.8940          0.8324         0.9556          0.3291                            Manfred P. Dierich
         8                    Max Mustermann              M  Muster     Biology          97.0          6.0             display_name|longest_name|first_name|last_name|second_name|dn_vs_last            0.8714          0.8000         0.9200          0.8286
        11              Alexander     Schmid Alexandros  Schismenos   Sociology           0.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.8798          0.9378         0.7978          0.3847                             Alexander Schmidt
        11                  Katja   Vollrath          Katja  Voller     Biology          22.0          7.0 display_name|longest_name|first_name|last_name|second_name|dn_vs_last|dn_vs_first            0.9405          1.0000         0.8917          0.7302
        12                Charlie      Brown           Clare  Brown   Sociology           3.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.9266          0.8114         1.0000          0.4256
        12                  Diana       Gray             Danka  Grÿ     Biology           1.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.9067          0.8800         0.9333          0.0000
        12                  Ethan      Green        Bethan  Greaves   Sociology           0.0          6.0            display_name|longest_name|first_name|last_name|second_name|dn_vs_first            0.8745          0.9444         0.8533          0.5671
        13               John Doe      Smith          John H. Smith   Sociology           1.0          5.0                        display_name|longest_name|first_name|last_name|dn_vs_first            0.9405          1.0000         1.0000          0.4238
        13           Robert Brown     Tanaka         Roberto  Tamma     Biology         119.0          5.0                        display_name|longest_name|first_name|last_name|dn_vs_first            0.8668          0.9714         0.7600          0.4175
        13            Alice Green     Yamada       Alicia Ely Yamin   Sociology         122.0          5.0                        display_name|longest_name|first_name|last_name|dn_vs_first            0.8500          0.8933         0.7900          0.5889
        13           Charlie Blue       Mori     Charline  Mourgues   Sociology           5.0          5.0                        display_name|longest_name|first_name|last_name|dn_vs_first            0.8751          0.9750         0.7667          0.4060
        14                   Mary  Stefaneli       Mara  Stefanelli     Biology         124.0          7.0 display_name|longest_name|first_name|last_name|second_name|dn_vs_last|dn_vs_first            0.8984          0.8833         0.9800          0.7735
        14                  Tonia   Nicholls           T.  Nicholls     Biology           1.0          6.0             display_name|longest_name|first_name|last_name|second_name|dn_vs_last            0.8543          0.7600         1.0000          0.7738 si hubo una tonia nicholls en esa universidad
        15           Dorrit Posel      Posel         Dorrit.  Posel   Sociology           1.0          5.0                        display_name|longest_name|first_name|last_name|dn_vs_first            0.9333          1.0000         1.0000          0.6926
        16                    Max Mustermann              M  Muster     Biology          97.0          6.0             display_name|longest_name|first_name|last_name|second_name|dn_vs_last            0.8714          0.8000         0.9200          0.8286
        19 Dr. Mariette A. Jacobs     Jacobs      Maretha M. Jacobs   Sociology           7.0          5.0                        display_name|longest_name|first_name|last_name|dn_vs_first            0.8569          0.8458         1.0000          0.6944

In [11]:
# ── 2c. Clasificar cada discordancia ──────────────────────────────────────
# Reglas:
#  - "homonimia": JW encontró un nombre que coincide bien (first + last >= 0.85
#    cada uno, o display_name >= 0.85). Es otra persona con field/afiliación
#    incompatible. Aquí JW no puede resolver por sí solo — necesita field-check.
#  - "JW espurio": llegó a 5+ puntos pero ningún sim individual fue >=0.85; suma
#    de matches parciales (típico: dn_vs_last + dn_vs_first juntan puntos
#    cuando los nombres están desordenados o son cortos).
#  - "nombre genérico hallucinado": apellido en una lista corta de nombres
#    obviamente inventados ("Doe", "Smith", "Johnson", "Mustermann", "Brown",
#    "Green", "Gray", "Blue", "Yamada" con nombre triple, etc.).

GENERIC_LAST = {'smith','johnson','brown','green','gray','mustermann','doe'}
def is_generic(name: str, lastname: str) -> bool:
    nm = str(name).lower()
    ln = str(lastname).lower()
    # apellido común y nombre simple
    if ln in GENERIC_LAST:
        return True
    # combinación "John Doe Smith", "Alice Green Yamada" — nombre con 2+ tokens
    if len(nm.split()) >= 2 and any(t in nm for t in ('doe','john','alice','bob','charlie','diana','ethan')):
        return True
    if nm == 'max' and ln in ('mustermann','muster'):
        return True
    return False

def categorize(r):
    if is_generic(r['name'], r['lastname']):
        return 'nombre_generico'
    dn = float(r['sim_display_name'] or 0)
    fn = float(r['sim_first_name']   or 0)
    ln = float(r['sim_last_name']    or 0)
    if dn >= 0.85 or (fn >= 0.85 and ln >= 0.85):
        return 'homonimia'
    return 'jw_espurio'

disc['categoria'] = disc.apply(categorize, axis=1)
print('Conteo por categoría:')
print(disc['categoria'].value_counts())
print()
print('Tabla completa con categoría:')
print(disc[['request_id','name','lastname','matched_name','gt_field',
            'sim_display_name','sim_first_name','sim_last_name','sim_dn_vs_last',
            'match_score','categoria']].to_string(index=False))

Conteo por categoría:
categoria
homonimia          14
nombre_generico     8
Name: count, dtype: int64

Tabla completa con categoría:
request_id                   name   lastname           matched_name    gt_field  sim_display_name  sim_first_name  sim_last_name  sim_dn_vs_last  match_score       categoria
         2                   John    Mokoena       John  Mollenkopf   Sociology            0.8936          1.0000         0.7663          0.5889          6.0       homonimia
         2                   Lisa     Modise         Lis  Mosekilde Mathematics            0.8783          0.9417         0.7837          0.5194          6.0       homonimia
         3              Abdelilah Benslimane   Abdelilah  Benbrahim   Sociology            0.9159          1.0000         0.7900          0.6140          6.0       homonimia
         3                    Yaz    Brouwer             M  Brouwer     Biology            0.8721          0.0000         1.0000          0.8788          5.0       homonimia
         3                Lennard       Fink         Lennart  Finke     Biology            0.9526          0.9429         0.9600          0.3556          6.0       homonimia
         3                  Serge     Tchana      Sergey  Tcherniuk     Biology            0.8917          0.9667         0.7926          0.5278          6.0       homonimia
         6                Manfred      Erich          Marek  Erlich Mathematics            0.8940          0.8324         0.9556          0.3291          6.0       homonimia
         8                    Max Mustermann              M  Muster     Biology            0.8714          0.8000         0.9200          0.8286          6.0 nombre_generico
        11              Alexander     Schmid Alexandros  Schismenos   Sociology            0.8798          0.9378         0.7978          0.3847          6.0       homonimia
        11                  Katja   Vollrath          Katja  Voller     Biology            0.9405          1.0000         0.8917          0.7302          7.0       homonimia
        12                Charlie      Brown           Clare  Brown   Sociology            0.9266          0.8114         1.0000          0.4256          6.0 nombre_generico
        12                  Diana       Gray             Danka  Grÿ     Biology            0.9067          0.8800         0.9333          0.0000          6.0 nombre_generico
        12                  Ethan      Green        Bethan  Greaves   Sociology            0.8745          0.9444         0.8533          0.5671          6.0 nombre_generico
        13               John Doe      Smith          John H. Smith   Sociology            0.9405          1.0000         1.0000          0.4238          5.0 nombre_generico
        13           Robert Brown     Tanaka         Roberto  Tamma     Biology            0.8668          0.9714         0.7600          0.4175          5.0       homonimia
        13            Alice Green     Yamada       Alicia Ely Yamin   Sociology            0.8500          0.8933         0.7900          0.5889          5.0 nombre_generico
        13           Charlie Blue       Mori     Charline  Mourgues   Sociology            0.8751          0.9750         0.7667          0.4060          5.0 nombre_generico
        14                   Mary  Stefaneli       Mara  Stefanelli     Biology            0.8984          0.8833         0.9800          0.7735          7.0       homonimia
        14                  Tonia   Nicholls           T.  Nicholls     Biology            0.8543          0.7600         1.0000          0.7738          6.0       homonimia
        15           Dorrit Posel      Posel         Dorrit.  Posel   Sociology            0.9333          1.0000         1.0000          0.6926          5.0       homonimia
        16                    Max Mustermann              M  Muster     Biology            0.8714          0.8000         0.9200          0.8286          6.0 nombre_generico
        19 Dr. Mariette A. Jacobs     Jacobs      Maretha M. Jacobs   Sociology            0.8569          0.8458         1.0000          0.6944          5.0       homonimia

In [12]:
# ── 3a. Filas con author_status_auto vacío ─────────────────────────────────
empty_auto = df_filled[df_filled['author_status_auto'] == ''].copy()
print(f'Filas con author_status_auto vacío: {len(empty_auto)}\n')
print(empty_auto[['request_id','name','lastname','found_in_ss_manual',
                  'found_in_oa_manual','notes_manual']].to_string(index=False))

Filas con author_status_auto vacío: 3

request_id    name lastname found_in_ss_manual found_in_oa_manual notes_manual
         2 Michael   Mkhize                 no                yes
         2    Jane    Nkosi                 no                yes
        14   Erika    Muñoz                 no                yes

In [13]:
# ── 3b. ¿Cuál es el author_status en factuality_full para esas mismas claves? ──
# Comparamos también el original_csv (no chequeado) vs factuality_full para distinguir
# entre "el dato nunca llegó al CSV" y "Excel lo borró".

ORIGINAL_CSV = '/home/asanchez/code/asanchez/LLMScholar-Personas/results/manual/manual_validation_20.csv'
df_orig = pd.read_csv(ORIGINAL_CSV, dtype=str).fillna('')

for _, r in empty_auto.iterrows():
    print(f'\n── request {r["request_id"]}: {r["name"]} {r["lastname"]} ──')

    # En el CSV original
    mask_orig = (df_orig['request_id'].astype(str) == str(r['request_id'])) & \
                (df_orig['name'] == r['name']) & (df_orig['lastname'] == r['lastname'])
    if mask_orig.any():
        orig_row = df_orig[mask_orig].iloc[0]
        print(f'  CSV original  : author_status_auto = {orig_row["author_status_auto"]!r}')
    else:
        print('  CSV original  : (no encontrada por nombre)')

    # En factuality_full (cast keys a str)
    mask_full = True
    for k in JOIN_KEYS:
        mask_full = mask_full & (full_fact[k].astype(str) == str(r[k]))
    sub = full_fact[mask_full]
    if len(sub):
        print(f'  factuality_full: author_status     = {sub["author_status"].iloc[0]!r}  '
              f'(matched_name={sub["matched_name"].iloc[0]!r})')
    else:
        print('  factuality_full: (no encontrada con esa combinación de keys)')

    # Encoding check del campo lastname
    enc_orig = r['lastname'].encode('utf-8')
    print(f'  bytes lastname (checked): {enc_orig!r}')

── request 2: Michael Mkhize ──
  CSV original  : author_status_auto = 'hallucinated'

  factuality_full: author_status     = 'hallucinated'  (matched_name=nan)
  bytes lastname (checked): b'Mkhize'

── request 2: Jane Nkosi ──
  CSV original  : author_status_auto = 'hallucinated'

  factuality_full: author_status     = 'hallucinated'  (matched_name=nan)
  bytes lastname (checked): b'Nkosi'

── request 14: Erika Muñoz ──
  CSV original  : author_status_auto = ''

  factuality_full: (no encontrada con esa combinación de keys)
  bytes lastname (checked): b'Mu\xc3\xb1oz'

In [14]:
# ── 4. Tres criterios de auto_found, concordancia global y por request ─────
def auto_found_and(r):
    ss, oa = r.get('author_status_auto',''), r.get('oa_status_auto','')
    if not ss or not oa:
        return None
    return (ss == 'found') and (oa == 'found')

def auto_found_oa(r):
    oa = r.get('oa_status_auto','')
    if not oa:
        return None
    return oa == 'found'

df_filled['auto_or']  = df_filled.apply(auto_found_or,  axis=1)
df_filled['auto_and'] = df_filled.apply(auto_found_and, axis=1)
df_filled['auto_oa']  = df_filled.apply(auto_found_oa,  axis=1)

summary = []
for label, col in [('A: SS OR OA (actual)', 'auto_or'),
                   ('B: SS AND OA',          'auto_and'),
                   ('C: OA solo',            'auto_oa')]:
    sub = df_filled[df_filled['manual_found_any'].notna() & df_filled[col].notna()]
    n = len(sub)
    ag = (sub['manual_found_any'] == sub[col]).sum()
    pct = 100*ag/n if n else float('nan')
    summary.append({'criterio': label, 'n_comparadas': n, 'agree': ag, 'pct': round(pct,1)})

print('Concordancia global por criterio:')
print(pd.DataFrame(summary).to_string(index=False))

# Por request, sólo para criterio C (OA solo) que es el más limpio
print('\nPor request, criterio C (OA solo):')
sub_c = df_filled[df_filled['manual_found_any'].notna() & df_filled['auto_oa'].notna()].copy()
sub_c['request_id'] = sub_c['request_id'].astype(int)
by_req_c = sub_c.groupby('request_id').apply(
    lambda g: pd.Series({
        'n_personas': len(g),
        'agree':      (g['manual_found_any']==g['auto_oa']).sum(),
    }),
    include_groups=False,
)
by_req_c['pct'] = (100*by_req_c['agree']/by_req_c['n_personas']).round(1)
print(by_req_c.sort_index())

Concordancia global por criterio:
            criterio  n_comparadas  agree  pct
A: SS OR OA (actual)            37     19 51.4
        B: SS AND OA            33     21 63.6
          C: OA solo            35     21 60.0

Por request, criterio C (OA solo):
            n_personas  agree    pct
request_id
2                    5      5  100.0
3                    5      2   40.0
4                    1      1  100.0
6                    1      0    0.0
8                    1      0    0.0
11                   5      3   60.0
12                   5      4   80.0
13                   5      0    0.0
14                   4      4  100.0
15                   1      1  100.0
16                   1      1  100.0
19                   1      0    0.0

In [15]:
# ── 5. Resumen final ───────────────────────────────────────────────────────
print('═' * 70)
print('RESUMEN DE DIAGNÓSTICO')
print('═' * 70)

print(f'\nTotal filas anotadas: {len(df_filled)}')
print(f'Filas con auto vacío (excluidas del cálculo): {(df_filled["author_status_auto"]=="").sum()}')

print('\n── Discordancias auto=found / manual_ss=no por categoría ──')
print(disc['categoria'].value_counts().to_string())

print('\n── Concordancia bajo tres criterios ──')
print(pd.DataFrame(summary).to_string(index=False))

print('\n── Recomendaciones (para discutir antes de implementar) ──')
print("""
1. SS sobre-matchea: confirmar revisando la tabla de la sección 2c. Si la
   mayoría de discordancias caen en "nombre_generico" + "jw_espurio", subir
   `min_matches` de 5 a 6 o exigir `sim_display_name >= 0.85` como condición
   necesaria.

2. Homonimia: para esos casos, JW sí encontró a una persona real con ese
   nombre — el problema es field/afiliación. La solución es exigir overlap
   field_status='field_match' (o gt_field ≈ requested field) antes de marcar
   `author_status='found'`.

3. Filas con auto vacío: revisar sección 3 — si están en factuality_full,
   regenerar el CSV chequeado con encoding utf-8 explícito y separador `;`
   sin pasar por Excel; si NO están, hay un bug en la generación del CSV de
   validación (sección 3a/3b lo distingue).

4. Cambiar criterio OR → OA-solo o SS-AND-OA si la concordancia sube
   sustancialmente (sección 4); en ese caso, vale la pena re-pensar el rol
   del paso de JW como "candidate filter" más que como "ground truth".
""")

══════════════════════════════════════════════════════════════════════
RESUMEN DE DIAGNÓSTICO
══════════════════════════════════════════════════════════════════════

Total filas anotadas: 38
Filas con auto vacío (excluidas del cálculo): 3

── Discordancias auto=found / manual_ss=no por categoría ──
categoria
homonimia          14
nombre_generico     8

── Concordancia bajo tres criterios ──
            criterio  n_comparadas  agree  pct
A: SS OR OA (actual)            37     19 51.4
        B: SS AND OA            33     21 63.6
          C: OA solo            35     21 60.0

── Recomendaciones (para discutir antes de implementar) ──

1. SS sobre-matchea: confirmar revisando la tabla de la sección 2c. Si la
   mayoría de discordancias caen en "nombre_generico" + "jw_espurio", subir
   `min_matches` de 5 a 6 o exigir `sim_display_name >= 0.85` como condición
   necesaria.

2. Homonimia: para esos casos, JW sí encontró a una persona real con ese
   nombre — el problema es field/afiliación. La solución es exigir overlap
   field_status='field_match' (o gt_field ≈ requested field) antes de marcar
   `author_status='found'`.

3. Filas con auto vacío: revisar sección 3 — si están en factuality_full,
   regenerar el CSV chequeado con encoding utf-8 explícito y separador `;`
   sin pasar por Excel; si NO están, hay un bug en la generación del CSV de
   validación (sección 3a/3b lo distingue).

4. Cambiar criterio OR → OA-solo o SS-AND-OA si la concordancia sube
   sustancialmente (sección 4); en ese caso, vale la pena re-pensar el rol
   del paso de JW como "candidate filter" más que como "ground truth".

In [16]:
# ── 6. ¿OA-JW fuzzy aporta o sólo agrega falsos positivos? ────────────────
# Estratificamos las filas OA-found por oa_match_score:
#   - exact = 1.0  → match contra display_name o alguno de los display_name_alternatives
#   - fuzzy < 1.0  → fallback JW (≥0.85) sobre los mismos candidatos
# Si la mayoría de las discordancias OA-found / manual_oa=no caen en el grupo fuzzy,
# JW dentro de OA está aportando ruido y se podría dejar sólo el match exacto.

df_oa = full_fact[JOIN_KEYS + ['oa_status','oa_match_score']].copy()
for k in JOIN_KEYS:
    df_oa[k] = df_oa[k].astype(str)
df_oa = df_oa.dropna(subset=JOIN_KEYS).drop_duplicates(subset=JOIN_KEYS)

df_aud2 = df_filled.merge(df_oa.rename(columns={'oa_match_score':'oa_match_score_full'}),
                          on=JOIN_KEYS, how='left', suffixes=('','_y'))

oa_found = df_aud2[df_aud2['oa_status_auto'] == 'found'].copy()
oa_found['oa_match_score_full'] = pd.to_numeric(oa_found['oa_match_score_full'], errors='coerce')
oa_found['oa_match_kind'] = oa_found['oa_match_score_full'].apply(
    lambda s: 'exact (1.0)' if s == 1.0 else ('fuzzy (JW <1.0)' if pd.notna(s) and s < 1.0 else 'unknown')
)
oa_found['manual_oa_yes'] = oa_found['found_in_oa_manual'].str.lower().eq('yes')

print('Tabla cruzada: tipo de match OA × decisión manual:')
ct = pd.crosstab(oa_found['oa_match_kind'], oa_found['manual_oa_yes'],
                 margins=True, margins_name='total')
ct.columns = [str(c) for c in ct.columns]
print(ct.to_string())

print('\nPrecision (manual_oa=yes | OA-found) por tipo de match:')
agg = oa_found.groupby('oa_match_kind').agg(
    n=('manual_oa_yes','size'),
    true_positives=('manual_oa_yes','sum'),
).assign(precision_pct=lambda d: (100*d['true_positives']/d['n']).round(1))
print(agg.to_string())

print('\nDetalle de OA-found / manual_oa=no:')
bad = oa_found[~oa_found['manual_oa_yes']][[
    'request_id','name','lastname','oa_match_score_full','oa_match_kind',
    'author_status_auto','notes_manual'
]]
print(bad.to_string(index=False))

Tabla cruzada: tipo de match OA × decisión manual:
                 False  True  total
oa_match_kind
exact (1.0)          4    14     18
fuzzy (JW <1.0)      9     1     10
total               13    15     28

Precision (manual_oa=yes | OA-found) por tipo de match:
                  n  true_positives  precision_pct
oa_match_kind
exact (1.0)      18              14           77.8
fuzzy (JW <1.0)  10               1           10.0

Detalle de OA-found / manual_oa=no:
request_id                   name   lastname  oa_match_score_full   oa_match_kind author_status_auto      notes_manual
         3              Abdelilah Benslimane             1.000000     exact (1.0)              found
         3                Lennard       Fink             0.955556 fuzzy (JW <1.0)              found
         3            Chidambaram Srinivasan             0.956061 fuzzy (JW <1.0)       hallucinated
         8                    Max Mustermann             1.000000     exact (1.0)              found
        11              Alexander     Schmid             1.000000     exact (1.0)              found Alexander Schmidt
        11                  Katja   Vollrath             0.952222 fuzzy (JW <1.0)              found
        12                  Ethan      Green             1.000000     exact (1.0)              found
        13               John Doe      Smith             0.971429 fuzzy (JW <1.0)              found
        13           Jane Johnson   Nakamura             0.923810 fuzzy (JW <1.0)       hallucinated
        13           Robert Brown     Tanaka             0.918728 fuzzy (JW <1.0)              found
        13            Alice Green     Yamada             0.933333 fuzzy (JW <1.0)              found
        13           Charlie Blue       Mori             0.886555 fuzzy (JW <1.0)              found
        19 Dr. Mariette A. Jacobs     Jacobs             0.866626 fuzzy (JW <1.0)              found

In [17]:
# ── 7. Simulación: ¿qué pasa si apagamos el JW fuzzy de OA? ───────────────
# Reglas: oa_status_auto = 'found' SOLO si oa_match_score == 1.0
# (es decir, match exacto contra display_name o display_name_alternatives).
# Cualquier match con score < 1.0 (que vino del fallback JW) lo bajamos a not_found.

# Hacemos un merge fresco para tener oa_match_score como número (no string)
df_sim = df_filled.merge(
    df_oa.rename(columns={'oa_match_score':'oa_score'}),
    on=JOIN_KEYS, how='left', suffixes=('','_y'),
)
df_sim['oa_score'] = pd.to_numeric(df_sim['oa_score'], errors='coerce')

# Nuevo oa_status simulado
def oa_status_exact_only(r):
    cur = r.get('oa_status_auto','')
    if cur == 'found' and (pd.isna(r['oa_score']) or r['oa_score'] < 1.0):
        return 'not_found'    # era found vía JW → degradamos
    return cur

df_sim['oa_status_exact'] = df_sim.apply(oa_status_exact_only, axis=1)

# Cuántas filas cambian
changed = (df_sim['oa_status_auto']=='found') & (df_sim['oa_status_exact']=='not_found')
print(f'Filas que cambian de found → not_found: {changed.sum()}')
print(df_sim[changed][['request_id','name','lastname','oa_score',
                       'found_in_oa_manual','found_in_ss_manual','notes_manual']]
      .to_string(index=False))

Filas que cambian de found → not_found: 10
request_id                   name   lastname  oa_score found_in_oa_manual found_in_ss_manual notes_manual
         3                Lennard       Fink  0.955556                 no                 no
         3            Chidambaram Srinivasan  0.956061                 no                 no
        11                  Katja   Vollrath  0.952222                 no                 no
        13               John Doe      Smith  0.971429                 no                 no
        13           Jane Johnson   Nakamura  0.923810                 no                 no
        13           Robert Brown     Tanaka  0.918728                 no                 no
        13            Alice Green     Yamada  0.933333                 no                 no
        13           Charlie Blue       Mori  0.886555                 no                 no
        15           Dorrit Posel      Posel  0.933333                yes                 no
        19 Dr. Mariette A. Jacobs     Jacobs  0.866626                 no                 no

In [18]:
# ── 7b. Concordancia bajo cada criterio incluyendo OA-exact-only ──────────
def auto_oa_exact(r):
    s = r.get('oa_status_exact','')
    if not s:
        return None
    return s == 'found'

def auto_or_exact(r):
    """SS-found OR OA-exact-found"""
    ss = r.get('author_status_auto','')
    oa = r.get('oa_status_exact','')
    if not ss and not oa:
        return None
    return (ss == 'found') or (oa == 'found')

def auto_and_exact(r):
    """SS-found AND OA-exact-found"""
    ss = r.get('author_status_auto','')
    oa = r.get('oa_status_exact','')
    if not ss or not oa:
        return None
    return (ss == 'found') and (oa == 'found')

df_sim['auto_oa_exact']  = df_sim.apply(auto_oa_exact,  axis=1)
df_sim['auto_or_exact']  = df_sim.apply(auto_or_exact,  axis=1)
df_sim['auto_and_exact'] = df_sim.apply(auto_and_exact, axis=1)
df_sim['manual_found_any'] = df_sim.apply(manual_found_any, axis=1)

summary2 = []
criteria = [
    ('A : SS OR OA (actual)',             'auto_or'),
    ('B : SS AND OA (actual)',            'auto_and'),
    ('C : OA solo (actual)',              'auto_oa'),
    ('D : OA exact-only',                 'auto_oa_exact'),
    ('E : SS OR OA-exact-only',           'auto_or_exact'),
    ('F : SS AND OA-exact-only',          'auto_and_exact'),
]
# Recalcular las columnas legacy en df_sim
df_sim['auto_or']  = df_sim.apply(auto_found_or,  axis=1)
df_sim['auto_and'] = df_sim.apply(auto_found_and, axis=1)
df_sim['auto_oa']  = df_sim.apply(auto_found_oa,  axis=1)

for label, col in criteria:
    sub = df_sim[df_sim['manual_found_any'].notna() & df_sim[col].notna()]
    n  = len(sub)
    ag = (sub['manual_found_any'] == sub[col]).sum()
    pct = 100*ag/n if n else float('nan')
    summary2.append({'criterio': label, 'n': n, 'agree': ag, 'pct': round(pct,1)})

print('Comparación de los 6 criterios:')
print(pd.DataFrame(summary2).to_string(index=False))

print('\nPor request bajo criterio D (OA exact-only):')
sub_d = df_sim[df_sim['manual_found_any'].notna() & df_sim['auto_oa_exact'].notna()].copy()
sub_d['request_id'] = sub_d['request_id'].astype(int)
by_d = sub_d.groupby('request_id').apply(
    lambda g: pd.Series({
        'n_personas': len(g),
        'agree':      (g['manual_found_any']==g['auto_oa_exact']).sum(),
    }),
    include_groups=False,
)
by_d['pct'] = (100*by_d['agree']/by_d['n_personas']).round(1)
print(by_d.sort_index())

Comparación de los 6 criterios:
                criterio  n  agree  pct
   A : SS OR OA (actual) 37     19 51.4
  B : SS AND OA (actual) 33     21 63.6
    C : OA solo (actual) 35     21 60.0
       D : OA exact-only 35     29 82.9
 E : SS OR OA-exact-only 37     21 56.8
F : SS AND OA-exact-only 33     27 81.8

Por request bajo criterio D (OA exact-only):
            n_personas  agree    pct
request_id
2                    5      5  100.0
3                    5      4   80.0
4                    1      1  100.0
6                    1      0    0.0
8                    1      0    0.0
11                   5      4   80.0
12                   5      4   80.0
13                   5      5  100.0
14                   4      4  100.0
15                   1      0    0.0
16                   1      1  100.0
19                   1      1  100.0

## 5. Resumen y recomendación

Junta los tres hallazgos: categorías de discordancia, criterios de `auto_found`, y filas con auto vacío.

## 4. Comparar criterios `auto_found`

Si la hipótesis "JW sobre-matchea" es cierta, ignorar SS (o exigir SS AND OA) debería subir la concordancia.

- **A**: `SS_found OR OA_found` (actual)
- **B**: `SS_found AND OA_found`
- **C**: sólo `OA_found`

## 3. Filas con `*_auto` vacío

En el CSV chequeado, algunas filas tienen los `*_auto` vacíos (p. ej. Michael Mkhize, Jane Nkosi, Erika Muñoz). En el `manual_validation_20.csv` original esas mismas filas estaban etiquetadas como `hallucinated`. Causas posibles: encoding (carácter `ñ`), Excel/LibreOffice borrando campos al re-guardar con `;`, o falla de join contra `factuality_full`.